spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Chamada
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        highlight_sql: true
    show-sql: true

server:
  port: 8080
  servlet:
    context-path: /